version: "3"
services:
  database:
    container_name: petbot-db
    image: postgres:13
    environment: 
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432